// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJkP2L6M88G8t-W6gFppmo1gIO_8yV1WM',
    appId: '1:1066620241323:web:e77bbafcf013e096183eee',
    messagingSenderId: '1066620241323',
    projectId: 'ecommerce-app-5b6d7',
    authDomain: 'ecommerce-app-5b6d7.firebaseapp.com',
    storageBucket: 'ecommerce-app-5b6d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbM198x6nnR71ahGRNu52AF52uhDHkr2U',
    appId: '1:1066620241323:android:6725497bf4194325183eee',
    messagingSenderId: '1066620241323',
    projectId: 'ecommerce-app-5b6d7',
    storageBucket: 'ecommerce-app-5b6d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPKWvmnA2se7qjpNZ5711FyxK6ZMd482w',
    appId: '1:1066620241323:ios:b7f52a76aba51729183eee',
    messagingSenderId: '1066620241323',
    projectId: 'ecommerce-app-5b6d7',
    storageBucket: 'ecommerce-app-5b6d7.firebasestorage.app',
    androidClientId: '1066620241323-bnmfcvmu71rmonn0ufr8u4qv1rhlu2g7.apps.googleusercontent.com',
    iosClientId: '1066620241323-00lvnvfv0vv3qe03jn7tgtd8psbbk2a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPKWvmnA2se7qjpNZ5711FyxK6ZMd482w',
    appId: '1:1066620241323:ios:b7f52a76aba51729183eee',
    messagingSenderId: '1066620241323',
    projectId: 'ecommerce-app-5b6d7',
    storageBucket: 'ecommerce-app-5b6d7.firebasestorage.app',
    androidClientId: '1066620241323-bnmfcvmu71rmonn0ufr8u4qv1rhlu2g7.apps.googleusercontent.com',
    iosClientId: '1066620241323-00lvnvfv0vv3qe03jn7tgtd8psbbk2a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fruitsHubDashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJkP2L6M88G8t-W6gFppmo1gIO_8yV1WM',
    appId: '1:1066620241323:web:5768a340f2224806183eee',
    messagingSenderId: '1066620241323',
    projectId: 'ecommerce-app-5b6d7',
    authDomain: 'ecommerce-app-5b6d7.firebaseapp.com',
    storageBucket: 'ecommerce-app-5b6d7.firebasestorage.app',
  );
}
